version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DB_HOST: db
  DB_NAME: workout_timer
  DB_USER: smeshko 
  DB_PASS: darkknight1

services: 
  
  app:
    image: workout-timer-backend:latest
    build:
      context: .
    environment: 
      <<: *shared_environment
    depends_on:
      - db
    ports: 
      - '8080:8080'

  db: 
    image: postgres:12.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: workout_timer
      POSTGRES_USER: smeshko 
      POSTGRES_PASSWORD: darkknight1
    ports:
      - "5432:5432"

volumes:
  db_data: