extension Workout {
    static let seed: [String: (category: String, sets: [(exerciseName: String, duration: Double)])] = [
        "Complete Routine": (Category.boxer.name, [
            (Exercise.freestyle.name, 180),
            (Exercise.recovery.name, 45),
            (Exercise.freestyle.name, 180),
            (Exercise.recovery.name, 45),
            (Exercise.freestyle.name, 180),
            (Exercise.recovery.name, 45),
            (Exercise.freestyle.name, 180),
            (Exercise.recovery.name, 45),
            (Exercise.freestyle.name, 180),
            (Exercise.recovery.name, 45),
            (Exercise.freestyle.name, 180),
            (Exercise.recovery.name, 60),
            (Exercise.heavyRopeJumping.name, 60),
            (Exercise.recovery.name, 30),
            (Exercise.pushUps.name, 60),
            (Exercise.recovery.name, 30),
            (Exercise.heavyRopeJumping.name, 60),
            (Exercise.recovery.name, 30),
            (Exercise.pushUps.name, 60),
            (Exercise.recovery.name, 30),
            (Exercise.heavyRopeJumping.name, 60),
            (Exercise.recovery.name, 30),
            (Exercise.pushUps.name, 60),
            (Exercise.recovery.name, 30),
            (Exercise.heavyRopeJumping.name, 30),
            (Exercise.recovery.name, 30),
            (Exercise.heavyRopeJumping.name, 30),
            (Exercise.recovery.name, 30),
            (Exercise.heavyRopeJumping.name, 30),
            (Exercise.recovery.name, 60),
            (Exercise.shadowBoxing.name, 120),
            (Exercise.recovery.name, 45),
            (Exercise.bicycles.name, 60),
            (Exercise.recovery.name, 30),
            (Exercise.shadowBoxing.name, 120),
            (Exercise.recovery.name, 45),
            (Exercise.oneArmShoulderTouches.name, 60),
            (Exercise.recovery.name, 30),
            (Exercise.shadowBoxing.name, 120),
            (Exercise.recovery.name, 45),
            (Exercise.boatToLowBoat.name, 60),
            (Exercise.recovery.name, 30),
            (Exercise.shadowBoxing.name, 120),
            (Exercise.recovery.name, 45),
            (Exercise.plank.name, 60),
            (Exercise.recovery.name, 10),
            (Exercise.lyingTStretch.name, 30),
            (Exercise.recovery.name, 5),
            (Exercise.lyingTStretch.name, 30),
            (Exercise.recovery.name, 5),
            (Exercise.lyingHamstringStretch.name, 30),
            (Exercise.recovery.name, 5),
            (Exercise.lyingHamstringStretch.name, 30),
            (Exercise.recovery.name, 5),
            (Exercise.quadRockers.name, 45)
        ])
    ]
}
