name: test
on: [push]


jobs:
  test_on_macos:
    runs-on: macOS-latest 
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4.1.app/Contents/Developer 
    steps:
    - uses: actions/checkout@v2
    - run: brew install postgresql
    - run: createdb -U postgres testingdb
    - run: xcrun swift test --enable-test-discovery --sanitize=thread

  test_on_ubuntu_xenial:
    env:
     DATABASE_PORT: 5433
     DATABASE_USERNAME: test
     DATABASE_PASSWORD: test
     DATABASE_NAME: test
     DATABASE_HOST: psql
    container:
      image: vapor/swift:5.2.2-xenial-ci
    services:
      psql:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_DB: test
          POSTGRES_PASSWORD: test

#     container:
#       image: vapor/swift:5.2.2-xenial-ci
    runs-on: ubuntu-latest
    
#     services:
#       psql:
#         image: postgres
#         ports:
#           - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: 'Running Integration Tests'    
        env:
         DATABASE_PORT: 5432
         DATABASE_USERNAME: test
         DATABASE_PASSWORD: test
         DATABASE_NAME: test
         DATABASE_HOST: psql
        run: swift test --enable-test-discovery --sanitize=thread

#     - run: apt update -y; apt install -y libsqlite3-dev
#     - run: apt-get update
#     - run: apt-get remove libpq5
#     - run: apt-get -yq install libpq-dev postgresql
# #     postgresql-client-12
#     - run: |
#           chmod +x ./scripts/db.sh
#           /bin/sh ./scripts/db.sh
#     - uses: actions/checkout@v2
#     - run: swift test --enable-test-discovery --sanitize=thread

  test_on_ubuntu_bionic: 
    container:
      image: vapor/swift:5.2.2-bionic-ci
    runs-on: ubuntu-latest
    steps:
    - run: apt update -y; apt install -y libsqlite3-dev 
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
